---
server:
  port: ${SERVER_PORT:8000}
  use-forward-headers: false
  servlet:
    context-path: /base



spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

#file.upload-dir=./uploads
